#服务端口
server:
  port: 8001

#数据库访问用户名和密码
spring:
  application:
    name: excise
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
# ===================================================================
# 数据库配置
# ===================================================================
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #      #mysql 相关配置
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://172.31.169.140:3306/book?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
      username: root
      password: iflytek
      # 配置初始化大小、最小、最大
      initial-size: 10
      max-active: 100
      min-idle: 10
      # 配置获取连接等待超时的时间(单位：毫秒)
      max-wait: 60000
      # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 应用向连接池申请连接，并且testOnBorrow为false时，连接池将会判断连接是否处于空闲状态，如果是，则验证这条连接是否可用
      test-while-idle: true
      # 如果为true，默认是false，应用向连接池申请连接时，连接池会判断这条连接是否是可用的
      test-on-borrow: false
      # 如果为true（默认false），当应用使用完连接，连接池回收连接的时候会判断该连接是否还可用
      test-on-return: false
    
    
#数据库访问地址
datasource:
  url: 172.31.169.140:3306/book
