#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.dgyu.entity
  
mybatis-plus:
  configuration:
    default-statement-timeout: 100
    jdbc-type-for-null: 'null'
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/*.xml


#jar外部配置logback.xml
logging:
  config: src/main/resources/logback-spring.xml
  #config: ../conf/logback-spring.xml