#服务端口
server:
  port: 8001

#数据库访问用户名和密码
spring:
  application:
    name: excise
  datasource:
    password: iflytek
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${datasource.url}?useUnicode=true&useSSL=false&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=100&useTimezone=true&serverTimezone=GMT%2B8
  profiles:
    active: dev
#数据库访问地址
datasource:
  url: 172.31.169.140:3306/book
