mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dgyu.entity

#jar外部配置logback.xml
logging:
  config: src/main/resources/logback-spring.xml
  #config: ../conf/logback-spring.xml